import { Inter } from "next/font/google";
import "./globals.css";
import Additem from "@/components/Additem";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "To-Do List",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="max-w-3xl mx-auto">
        <h1 className="text-3xl text-center mt-5 font-bold ">To-Do List mongoDB</h1>
        <Additem />

        {children}
        </div>
        </body>
    </html>
  );
}
